---
title: "P8105_HW6_yz4717"
author: "Yang Zhao"
date: "2023-12-02"
output: github_document
---

```{r import_needed_packages}
library(tidyverse)
library(modelr)
```

## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r building_model_q2}
weather_q2_df =
  weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    modeling = map(strap, \(data) lm(tmax ~ tmin + prcp, data = data)),
    mapping = map(modeling, broom::glance),
    result = map(modeling, broom::tidy)) |>
  select(.id, result, mapping) |> 
  unnest(result, mapping) |>
  select(.id, r.squared, term, estimate) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |>
  mutate(
    log_data = log(tmin * prcp)
  ) |>
  select(.id, r.squared, log_data)

head(weather_q2_df)
```

Then, I would like to plot the r_squared distribution.

```{r density_plot_r^2}

weather_q2_df |>
  ggplot(aes(x = r.squared)) +
  geom_density()+
  labs(x = "R_Squared",
       y = "Density",
       title = "The Density Plot of R_squared")

```

As can be seen from the above graph, the distribution is approximately normal, with the median of 0.917. 

After that, I plot the distribution of ($log(\hat{\beta_1} * \hat{\beta_2})$)

```{r density_plot_log}

weather_q2_df |>
  ggplot(aes(x = log_data)) +
  geom_density()+
  labs(x = "Log",
       y = "Density",
       title = "The Density Plot of Log Data")

```

* Confidence interval of ${r^2}$ and $log(\hat{\beta_1} * \hat{\beta_2})$

* Here comes the 95% CI of r_squared.

```{r quantile_r_squared}

quantile(
  pull(weather_q2_df,
       r.squared),
  probs = c(.025, .975))

```

* Here comes the 95% CI of $log(\hat{\beta_1} * \hat{\beta_2})$ excluding `NULL` data.

```{r quantile_log}

quantile(
  pull(weather_q2_df,
       log_data),
  probs = c(.025, .975),
  na.rm = TRUE)

```

## Problem 3


```{r import_data_q3}

birthweight_df =
  read_csv('data/birthweight.csv', na = c("", "NA", "Unknown"))

birthweight_df =
  birthweight_df |>
  mutate(
    babysex = case_match(
             babysex,
             1 ~ "male",
             2 ~ "female"),
    frace = case_match(
             frace,
             1 ~ "White", 
             2 ~ "Black", 
             3 ~ "Asian", 
             4 ~ "Puerto Rican", 
             8 ~ "Other", 
             9 ~ "Unknown"),
    malform = case_match(
             malform,
             0 ~ "absent",
             1 ~ "present"),
    mrace = case_match(
             mrace,
             1 ~ "White", 
             2 ~ "Black", 
             3 ~ "Asian", 
             4 ~ "Puerto Rican", 
             8 ~ "Other"),
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace))

head(birthweight_df)

```

```{r building_linear_model}

lm_q3 = lm(bwt ~ .,
           data = birthweight_df)

summary(lm_q3)

```

```{r prediction_residual}

birthweight_df |>
  add_predictions(lm_q3) |>
  add_residuals(lm_q3) |>
  ggplot(aes(x = pred,
             y = resid)) +
  geom_point(color = "black",
             alpha = .5) +
  geom_hline(yintercept = 0,
             linetype = "dashed",
             color = "blue") +
  labs(x = "Fitted",
       y = "Residuals",
       title = "The Plot of Birthweight Model")

```

```{r}

```

